@baseUrl = http://localhost:8000

###
# 1. Obtener Cookie CSRF (Este paso nunca cambia)
GET {{baseUrl}}/sanctum/csrf-cookie
Accept: application/json

###
# 2. Iniciar Sesión (Usando NUESTRO controlador)
POST {{baseUrl}}/login
Content-Type: application/json
Accept: application/json

{
    "email": "admin@ejemplo.com",
    "password": "password"
}

###
# 3. Obtener datos del usuario (Para verificar que el login funcionó)
GET {{baseUrl}}/api/v1/user
Accept: application/json


###
# 4. Probar una ruta protegida (Después de un login exitoso)
GET {{baseUrl}}/api/v1/classrooms
Accept: application/json


###
# 5. Cerrar Sesión
POST {{baseUrl}}/logout
Accept: application/json
